### ISSUE TITLE
Nature

### ISSUE THREAD

**Issue by nickschurch** [sciencefair-land/datasource-requests#6]
Someone has to ask for it, right?

**Comment by blahah** [comment]
To the extent that we can include Nature journals, they will be provided via PMC (#1).

Nature magazine itself has some articles deposited due to NIH rules: https://www.ncbi.nlm.nih.gov/pmc/?term=%22Nature%22%5Bjournal%5D

And Nature Comms (their only OA offering) is fully deposited in PMC: https://www.ncbi.nlm.nih.gov/pmc/?term=%22Nat%20Commun%22%5Bjournal%5D

Other Nature publications have small proportions of deposited content: https://www.ncbi.nlm.nih.gov/pmc/journals/?term=nature&titles=all&search=journals

**Comment by blahah** [comment]
In general there is nothing we can do to stop someone creating any datasource they want and sharing it with others - so someone could for example make a feed from all Nature's content if they could wrangle it into JATS - but we can't create datasources officially that obviously provoke (c) defence actions.

**Comment by blahah** [comment]
I'm going to close this because it's covered by PMC and/or EuropePMC
